---
grails:
    profile: web
    codegen:
        defaultPackage: au.com.redboxresearchdata.cm
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html: 
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            rss: application/rss+xml
            text: text/plain
            hal: 
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8

    hibernate:
        cache:
            queries: false
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none

---
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.postgresql.Driver
# Domain configuration
domain:
    curation_status_lookup:
        - in_progress
        - complete
        - failed
        - curating
    entry_type_lookup:
        - person
        - group
        - document
        - dataset
        - service
        - activity
# API configuration
api:
    job:
        init_status: in_progress
        error:
            nothing_to_curate:
                code: 400
                message: "What is there to curate?"
            failed_validation:
                code: 400
                message: "The API call did not contain the required parameters in the POST data: %1s"
            parse_error:
                code: 400
                message: "Failed to parse request."
            invalid_id_type:
                code: 400
                # The first argument is the supplied ID type
                message:  "No identity provider for '%1s' exists in the system."
            mismatch_type:
                code: 400
                # The first argument is the supplied type, secod is the existing type
                message: "Requested type (%1s) is a mismatch for the oid's existing type (%2s) for entry: %3s"
    import:
        exit_status: complete
        filters: ['metadata']
        error:
            nothing_to_import:
                code: 400
                message: "What is there to import?"
            parse_error:
                code: 400
                message: "Failed to parse request."

runner:
    job:
        max_recent: 100
        # Status runners
        curation_runners:
             - in_progress
             - curating
        # Each runner can have different sleep intervals, thread pools to cater to different processing loads.
        in_progress:
            thread_pool_count: 5
            sleep_time: 10000
        curating:
            thread_pool_count: 5
            sleep_time: 60000
#
# ID Provider configuration. Please note that IDs are case-sensitive and match to the "identifier_type" field in the request.
# Grails has the ability to merge configurations so potentially the list below is not all-inclusive, so do check out your config locations.
#
id_providers:
    enabled:
        - local
        # Commenting out the others until they are completed
        - nla
        # - handle
    # ID: 'local' Identity provider
    local:
        className: au.com.redboxresearchdata.cm.id.local.LocalIdProvider
        templates:
            dataset:
                template: "urn:uri:[[UUID]]"
                validators: ["URN"]
            person:
                template: "http://www.example.edu.au/people/[[OID]]"
                validators: ["URL"]
            group:
                template: "http://www.some.site.com/group/[[INC]]"
    nla:
        className: au.com.redboxresearchdata.cm.id.nla.NlaIdProvider
        sru:
            recordSchema: "urn:isbn:1-931666-33-4"
            version: "1.1"
            recordPacking: "xml"
        mq:
            queue: "oaiPmhFeed"
        templates:
            person: "templates/person.json"
## 
## Environment-specific configuration
##
environments:
    development:
         id_providers:
            nla:
                sru:
                    url: "http://www-test.nla.gov.au/apps/srw/search/peopleaustralia"
                mq:
                    broker_url: "tcp://localhost:9301"
         dataSource:
            dbCreate: create-drop
            username: curationmanager
            password: zrTAqx&cbOjE^2OZ94nr5QNY4Wxyb8IAZbY1nYkqCz@&@Q3&v4#v2Q@qL3x7L4#QDnr5Hw9P*QWgAsv!@
            url: "jdbc:postgresql://localhost/curationmanager_dev"
    test:
        runner:
            job:
                curating:
                    thread_pool_count: 5
                    sleep_time: 10000
        id_providers:
            nla:
                sru:
                    url: "http://localhost:8081/apps/srw/search/peopleaustralia"
                mq:
                    broker_url: "tcp://localhost:9302"
        dataSource:
            dbCreate: create
            username: curationmanager
            password: zrTAqx&cbOjE^2OZ94nr5QNY4Wxyb8IAZbY1nYkqCz@&@Q3&v4#v2Q@qL3x7L4#QDnr5Hw9P*QWgAsv!@
            url: "jdbc:postgresql://localhost/curationmanager_test"
            
    staging:
        server:
            port: 8081
        id_providers:
            nla:
                sru:
                    url: "http://www-test.nla.gov.au/apps/srw/search/peopleaustralia"
                mq:
                    broker_url: "tcp://localhost:9301"
        dataSource:
            username: curationmanager
            password: zrTAqx&cbOjE^2OZ94nr5QNY4Wxyb8IAZbY1nYkqCz@&@Q3&v4#v2Q@qL3x7L4#QDnr5Hw9P*QWgAsv!@
            url: "jdbc:postgresql://localhost/curationmanager_staging"
                
    production:
        id_providers:
            nla:
                sru:
                    url: "http://www-test.nla.gov.au/apps/srw/search/peopleaustralia"
                mq:
                    broker_url: "tcp://localhost:9301"
        dataSource:
            username: curationmanager
            password: zrTAqx&cbOjE^2OZ94nr5QNY4Wxyb8IAZbY1nYkqCz@&@Q3&v4#v2Q@qL3x7L4#QDnr5Hw9P*QWgAsv!@
            url: "jdbc:postgresql://localhost/curationmanager_prod"
            