package au.com.redboxresearchdata.curationmanager.constants

class CurationManagerConstants {

	static final String  OID = "oid";
	static final String NLA = "nla";
	static final String ASC = "asc";
	static final String METADATA = "metadata";
	static final String JOIN = "join";
	static final String TYPE = "type";
	static final String TITLE = "title";
	static final String STATUS_400 =  "400";
	static final String STATUS_404 = "404";
	static final String STATUS_500 =  "500";
	static final String STATUS = "status";
	static final String  TYPE_NULL = "type.null" 
	static final String TYPE_EMPTY = "type.empty"
	static final String TITLE_NULL = "title.null"
	static final String TITLE_EMPTY = "title.empty"
	static final String JOB_ID_NULL= "job.id.null"
	static final String OID_NULL = "oid.null";
	static final String OID_EMPTY= "oid.empty"
	static final String OID_EXISTS = "oid.exists"
	static final String JOBID_EXISTS = "jobid.exists"
	static final String IDENTIFIER = "identifier";
	static final String DATE_CREATED = "date_created"
	static final String DATE_COMPLETED = "date_completed"
	static final String REQUEST_PARAMS_NULL = "requestparams.null"
	static final String CURATION_JOB_ITEMS = "CurationJobItems";
	static final String DUPLICATE_OID = "duplicate.oids"
	static final String  FAILED_TO_PROCESS_REQUIRED_IDENTIFIERS = "failed.to.process.required.identifiers"
	static final String DUPLICATE_IDENTIFIER_TYPE = "duplicate.identifier.type"
	static final String IDENTITY_SERVICE_FAILED = "curationmanager.identityService.failed"
	static final String REQUIRED_IDENTIFIER_TYPE_NULL = "requiredidentifiertype.null"
	static final String REQUIRED_IDENTIFIER_TYPE_EMPTY = "requiredidentifiertype.empty"
	static final String OID_ENTRY_TYPE_EXISTS = "oid.entry.type.exists"
	static final String  UNEXPECTED_ERROR = "unexpected.error";
	static final String OID_IDENTIFIER_TYPE_EXISTS = "oid.identifier.type.exisists"
	static final String ERROR_MESSAGE_SERVICE_NOT_AVAILABLE = "Identity Provider Service not available";
	static final String ERROR_MESSAGE_CONTACT_SYSTEM_ADMININSTRATOR = "Contact System Administrator";
	static final String FAILED = "FAILED";
	static final String CURATING = "CURATING"
	static final String COMPLETED = "COMPLETED"
    static final String IN_PROGRESS = "IN_PROGRESS";
	static final String IDENTIFIER_TYPE = "identifier_type";
	static final String PERSON = "person";
	static final String DOCUMENT = "document";
	static final String Group = "group";
    static final String STATUS_PENDING = "PENDING";
	static final String ENTRY = "entry";
	static final String CURATIONS = "curations";
	static final String CURATION = "curation";
	static final String INC_DELIMITER = "[[INC]]";
	static final String OID_DELIMITER = "[[OID]]";
	static final String ENTRY_ID = "entry.id";
	static final String REQUIRED_IDENTIFIERS = "required_identifiers";
	static final String REQIDENTIFIERS  = "requiredIdentifiers"
	static final String FAILED_VALIDATION = "Failed Validation";
	static final String CURATIONMANAGER_JOB_LOOKUP_FAILED = "curationmanager.job.lookup.failed"
	static final String CURATIONMANAGER_IDENTITYSERVICE_FAILED = "curationmanager.identityService.failed"
	static final String CURATIONMANAGER_IDENTITYSERVICE_IDENTIFIER_NULL = "curationmanager.identityService.identifier.null"
	static final String CURATIONMANAGER_IDENTITYSERVICE_NO_RESULT = "curationmanager.identityService.no.result";
}
